networks:
  shared_network:
    external: true

volumes:
  postgres_data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guru
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./job-service/docker/tables.sql:/docker-entrypoint-initdb.d/tables.sql  
    networks:
      - shared_network