version: '4.0.7'
networks:
  shared_network:
    external: true

services:
  feedback-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9005:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/guru
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - my_cassandra
    networks:
      - shared_network

  my_cassandra:
    image: cassandra
    container_name: my_cassandra
    ports:
      - "9042:9042"
    networks:
      - shared_network
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
