apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: job-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: job
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60  # 1 minutes stabilization window for scaling down
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Scale down by 1 pod at most every 60 seconds
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60  # Scale up by 1 pod at most every 60 seconds