spring:
  redis:
    host: localhost
    port: 6379
    timeout: 6000
    jedis:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1

  datasource:
    url: jdbc:mysql://localhost:3306/guru_payment_db
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      group-id: "guru-payment-group"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
