version: '3.9'

networks:
  payment-network:
    driver: bridge

services:
  postgres:
    container_name: my-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guru
    networks:
      - payment-network
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "56788:56788"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - payment-network

  springapipayment:
    build: .
    image: springapipayment
    container_name: payment-app
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/guru
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=56788
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - payment-network
    depends_on:
      - postgres
      - rabbitmq
#    restart: unless-stopped
