#services:
#  db:
#    container_name: postgres
#    image: postgres
#    environment:
#      POSTGRES_USER: basbosa
#      POSTGRES_PASSWORD: password
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5332:5432"
#    networks:
#      - db
#    restart: unless-stopped
#
#networks:
#  db:
#    driver: bridge
#
#volumes:
#  db:
#
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: basbosa
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

