services:
  job-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/guru
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
      - redis-server
      - rabbitmq

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guru
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./docker/tables.sql:/docker-entrypoint-initdb.d/tables.sql

  redis-server:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
