name: Postgres CI

on:
  push:
    branches: [ "TempBranch" ]
    paths:
      - 'database/SQL/*'
#  pull_request:
#    branches: [ "TempBranch" ]
#    paths:
#      - 'database/SQL/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: minamo0o2
          password: Za+8612085

      - name: Build and push image
        run: |
          IMAGE_NAME="custom-postgres-CI"
          DOCKERFILE="Dockerfile"
          TAG="minamo0o2/scalabol:$IMAGE_NAME"
          docker build . -t $IMAGE_NAME -f $DOCKERFILE
          docker tag $IMAGE_NAME $TAG
          docker push $TAG
