apiVersion: v1
kind: Service
metadata:
  name: freelancer
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "8080"
spec:
  selector:
    app: freelancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

