apiVersion: apps/v1
kind: Deployment
metadata:
  name: freelancer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: freelancer
  template:
    metadata:
      labels:
        app: freelancer
    spec:
      initContainers:
        - name: init-delay
          image: busybox
          command: ['sh', '-c', 'sleep 30']
      containers:
        - name: freelancer
          image: minamo0o2/scalabol:freelancer-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/guru
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "750m"
